version: "3.8"

services:

  api-pokemon:
    image: fmarxds/api-fiap-containers-pokemon
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      SERVER_PORT: 5000
      MONGODB_HOST: mongodb
    networks:
      - fiap
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  web--pokemon:
    image: runageinc/pokemon-frontend-test
    depends_on:
      - api--pokemon
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_HOST: api-pokemon
    networks:
      - fiap
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - fiap
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  fiap: