spring.application.name: api--pokemon

server.port: ${SERVER_PORT:5000}

logging.level:
  org.zalando.logbook: TRACE
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:db_pokemon}
  username: ${MONGODB_USERNAME:admin}
  password: ${MONGODB_PASSWORD:admin}
  authentication-database: ${MONGODB_AUTH_DATABASE:admin}

management:
  endpoints:
    web:
      cors:
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
        exposed-headers: "Access-Control-Allow-Origin,Origin"
        allow-credentials: false